"""Modified Models

Revision ID: 82dce582843d
Revises: e0a0fb2e4ae5
Create Date: 2022-06-16 13:25:53.432533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82dce582843d'
down_revision = 'e0a0fb2e4ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('posts', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
