"""Added file_path to post models

Revision ID: a0a5f2c3a345
Revises: 9f97cdd69715
Create Date: 2022-06-14 12:40:25.736903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a5f2c3a345'
down_revision = '9f97cdd69715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'file_path')
    # ### end Alembic commands ###
