"""Modified User and Post models

Revision ID: a5ded6e01767
Revises: 800218f4aba2
Create Date: 2022-05-30 11:05:57.102366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ded6e01767'
down_revision = '800218f4aba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_reviewed', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('rejected_reason', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('posts', 'rejected_reason')
    op.drop_column('posts', 'is_accepted')
    op.drop_column('posts', 'is_reviewed')
    # ### end Alembic commands ###
