"""Models Changed

Revision ID: d6a143871eff
Revises: eee132b8c439
Create Date: 2022-05-30 20:39:44.743025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a143871eff'
down_revision = 'eee132b8c439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('posts', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
