"""Modified models

Revision ID: eee132b8c439
Revises: a5ded6e01767
Create Date: 2022-05-30 16:57:39.865124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee132b8c439'
down_revision = 'a5ded6e01767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categories', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'categories')
    # ### end Alembic commands ###
